# spring.application.name=social

spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27018
      database: users
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.4849f30c8208f619
            clientSecret: b0dee2f7ad96fee5b0e09ef340e19b2db39d8016
            scope: read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id