version: '3'
services:

######### BASE DE DONNEES #########

  mongodb-node:
    image: mongo:6-jammy
    networks:
      - node-network
    ports:
      - '27017:27017'
    volumes:
      - dbdata_node:/data/db
    restart: always




  mongodb-java:
    container_name: mongodb-java
    image: mongo:6-jammy
    ports:
      - '27018:27017'
    volumes:
      - dbdata_java:/data/db
    networks:
      - java-network



######### BACK #########

  javascript:
    build: ./back/commentaires
    volumes: 
    - ./back/commentaires/:/app
    networks:
      - node-network
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - mongodb-node
    
  java:
    container_name: java
    build: ./back/connexion
    volumes:
      - ./back/connexion:/home/app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb-java
    networks:
      - java-network

  python:
    build: ./back/images
    volumes:
      - ./back/images:/app/images
    ports:
      - "5000:5000" 




######### FRONT #########

  react-front:
    build: ./front/react
    # volumes:
    #   - ./front/react:/app
    ports:
     - "5173:5173"
    depends_on:
     - mongodb-node
     - javascript
     - java
     - python





######### NETWORKS #########


networks:
  java-network:
  node-network:


######### VOLUMES #########


volumes:
  dbdata_java:
  dbdata_node:
